USE [master]
GO

/****** Object:  Database [Hospital]    Script Date: 11/17/18 6:02:17 PM ******/
CREATE DATABASE [Hospital]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hospital', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Hospital.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Hospital_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Hospital_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Hospital] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hospital].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hospital] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hospital] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hospital] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hospital] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hospital] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hospital] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hospital] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hospital] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hospital] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hospital] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hospital] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hospital] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hospital] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hospital] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hospital] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Hospital] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hospital] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hospital] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hospital] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hospital] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hospital] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Hospital] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Hospital] SET RECOVERY FULL 
GO

ALTER DATABASE [Hospital] SET  MULTI_USER 
GO

ALTER DATABASE [Hospital] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Hospital] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Hospital] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Hospital] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Hospital] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Hospital] SET QUERY_STORE = OFF
GO

USE [Hospital]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Hospital] SET  READ_WRITE 
GO


USE [Hospital]
GO

/****** Object:  Table [dbo].[Patient]    Script Date: 11/17/18 6:03:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Patient](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[Town] [varchar](50) NULL,
	[Temperature] [decimal](5, 1) NULL,
	[Pulse] [int] NULL,
 CONSTRAINT [PK_Patient] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Hospital]
GO

/****** Object:  Table [dbo].[Medication]    Script Date: 11/17/18 6:04:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Medication](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[PatientId] [bigint] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Dose] [varchar](50) NULL,
	[StartDate] [date] NULL,
	[StopDate] [date] NULL,
 CONSTRAINT [PK_Medication] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Medication]  WITH CHECK ADD  CONSTRAINT [FK_Medication_Patient] FOREIGN KEY([PatientId])
REFERENCES [dbo].[Patient] ([Id])
GO

ALTER TABLE [dbo].[Medication] CHECK CONSTRAINT [FK_Medication_Patient]
GO



USE [master]
GO

CREATE LOGIN [hospital-dbo] WITH PASSWORD=N'hospital-dbo', DEFAULT_DATABASE=[Hospital], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO


USE [Hospital]
GO

CREATE USER [hospital-dbo] FOR LOGIN [hospital-dbo]
GO

EXEC sp_addrolemember N'db_owner', N'hospital-dbo'
GO
